---
#@ load("funcs.lib.yml", "slack_hook", "pr_hook")
#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#@ env = data.values.env

#!  JOBS

jobs:
  - name: set-pipeline
    plan:
      - get: src
        params:
          depth: 1
        trigger: true
      - get: pipeline-tasks
      - get: general-task
      - task: boot
        image: general-task
        file: pipeline-tasks/tasks/boot.yml
        params:
          ENV_OVERRIDE: ((deploy-env))
      - set_pipeline: self
        file: compiled/set-pipeline.yml
        instance_vars:
          deploy-env: ((deploy-env))

  - name: new-deploys
    plan:
      - get: src
        params:
          depth: 1
      - get: s3
        trigger: true
      - get: general-task
      - task: ls-sites
        file: src/ci/partials/ls-sites.yml
        image: general-task
      - load_var: sites
        file: s3/sites.json
      - across:
          - var: site
            values: ((.:sites))
            max_in_flight: 20
        do:
          - task: deploy-site-gantry
            file: src/ci/partials/deploy.yml
            image: general-task
            params:
              _: #@ template.replace(data.values.env_cf_editor)
              CF_APP_NAME: ((.:site.name))-site-gantry
              CF_MANIFEST: src/.cloudgov/manifest.yml
              CF_VARS_FILE: src/.cloudgov/vars/((deploy-env)).yml
              CF_PATH: src
              SITE: ((.:site.name))
              API_KEY: ((.:site.apiKey))

#!  RESOURCES

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: git@github.com:((pages-website-watcher-repository-path))
      branch: main
      commit_verification_keys: ((cloud-gov-pages-gpg-keys))
      private_key: ((pages-gpg-operations-github-sshkey.private_key))

  - name: general-task
  - name: pipeline-tasks
  - name: s3
    type: s3-resource
    source:
      access_key_id: ((editor-site-data-access-key-id-((deploy-env))))
      secret_access_key: ((editor-site-data-secret-access-key-((deploy-env))))
      bucket: ((editor-site-data-bucket-((deploy-env))))
      region: us-gov-west-1

#!  RESOURCE TYPES

resource_types:
  - name: git
  - name: registry-image
  - name: s3-resource
